name: build-system-a-team-a
on:
  push:
    branch: development
  workflow_dispatch:
jobs:
  build-from-source:
    uses: ga-framework-poc/cicd-manager/.github/workflows/build-from-source.yml@development
    with:
      system-name: system-a
    secrets: inherit
  deploy-to-all:
    needs: gather-test-environments
    uses: ga-framework-poc/cicd-manager/.github/workflows/promote.yml@development
    with:
      system-name: system-a