name: test-workflow
on:
  workflow_dispatch:
jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
    - id: test-runner
      name: test-runner
      run: |
        set -ex
        echo "whereis podman: $(whereis podman)"
        echo "whereis podman: $(whereis docker)"
        set +ex
